name: Build and Test on Push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gradle_build_test:
    name: Gradle build and test
    strategy:
      matrix:
        os: [ ubuntu-latest,macos-latest ]
#        java-version: [ 11, 17, 19 ]
        java-version: [ 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}
          check-latest: true
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
