name: Generate KDoc

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  update_kdoc:
    name: Generate KDoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          check-latest: true
          cache: gradle
      - name: Generate KDoc
        uses: gradle/gradle-build-action@v2
        with:
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PAGE_PROJECT }}
          directory: ./build/dokka/html
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
