name: Generate KDoc

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  update_kdoc:
    name: Generate KDoc
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          check-latest: true
          cache: gradle
      - name: Generate KDoc
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload KDoc
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/dokka/html
      - name: Deploy KDoc to GitHub Pages
        uses: actions/deploy-pages@v1
